[mypy]
warn_unused_configs = True

[mypy-wonderwords.*]
follow_untyped_imports = True

[mypy-tkcalendar.*]
follow_untyped_imports = True

[mypy-tktimepicker.*]
follow_untyped_imports = True

[mypy-tktooltip.*]
follow_untyped_imports = True