[mypy]
warn_unused_configs = True
disable_error_code = import-untyped

[mypy-wonderwords.*]
follow_untyped_imports = True

[mypy-tkcalendar.*]
follow_untyped_imports = True

[mypy-tktimepicker.*]
follow_untyped_imports = True

[mypy-tktooltip.*]
follow_untyped_imports = True

[parameterized.*]
follow_untyped_imports = True